### PR TITLE
Delete intermediate tables after use

### LINKED ISSUE #86: Lacking clean up of temporary tables in `update_snapshot`
**Describe the bug**
Over at [`diseasystore`](https://github.com/ssi-dk/diseasystore/) we have been using SCDB at scale. 
Recently, we have been having intermittent issues (see issue: https://github.com/ssi-dk/diseasystore/issues/113).
When investigating, it seems the issue may be related to excessive creation of `dbplyr_###` tables which are not being cleaned up during use. 

These are cleared when the connection is dropped, but if many operations are done on a connection before closing, issues may arrise.
(if I am right about the source of the problem).

Regardless, `update_snapshot` can reduce its footprint which I think it should do.

**To Reproduce**
```
conn <- DBI::dbConnect(RSQLite::SQLite())
mtcars <- dplyr::copy_to(conn, mtcars, "tmp")

# Configure logger for example
logger <- SCDB::Logger$new(
  output_to_console = FALSE,
  log_table_id = NULL,
  log_conn = NULL,
  warn = FALSE
)

# No dbplyr_#### tables before the call to update_snapshot
print(SCDB::get_tables(conn, show_temp = TRUE))
#>   schema table
#> 1   temp   tmp

SCDB::update_snapshot(
  .data = head(mtcars, 3),
  conn = conn,
  db_table = "mtcars",
  timestamp = as.POSIXct("2020-01-01 11:00:00"), 
  logger = logger
)
#> NULL

# After the call to update_snapshot, 2 dbplyr_#### tables
print(SCDB::get_tables(conn, show_temp = TRUE))
#>   schema      table
#> 1   <NA>     mtcars
#> 2   temp dbplyr_002
#> 3   temp dbplyr_001
#> 4   temp        tmp


SCDB::update_snapshot(
  .data = head(mtcars, 6),
  conn = conn,
  db_table = "mtcars",
  timestamp = as.POSIXct("2020-01-01 11:00:00"),
  logger = logger
)
#> NULL

# After an additional call to update_snapshot, 5 dbplyr_#### tables
print(SCDB::get_tables(conn, show_temp = TRUE))
#>   schema      table
#> 1   <NA>     mtcars
#> 2   temp dbplyr_005
#> 3   temp dbplyr_004
#> 4   temp dbplyr_003
#> 5   temp dbplyr_002
#> 6   temp dbplyr_001
#> 7   temp        tmp
```

**Expected behavior**
`update_snapshot` should contain itself to a minimal footprint.

**Screenshots**
N/A

**Provide output from `sessionInfo()`**
N/A

* [x] I have checked that the bug is not already described in [open issues](https://github.com/ssi-dk/SCDB/issues?q=is%3Aopen)

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by RasmusSkytte**
### Intent
Fixes #86

### Approach
* A new function `defer_db_cleanup` was added which uses `withr::defer` to remove the specified table when the function exits.
By inserting this function into our functions when we generate new tables, the intermediate tables created will automatically be removed once the function returns.

EDIT: to clarify, it will delete the table once the parent of `defer_db_cleanup` exits, not when `defer_db_cleanup` exits.

* A new function `unique_table_name()` is added (inspired by dbplyrs internal function of the same name) which gives an easy way to create table names like `SCDB_###` for tables.
By using this function, we can keep track of the tables that we explicitly need and which should be kept when the function returns (which we can give the "SCDB_" prefix) and those we implicitly create in intermediate computations and should not remain after the function returns (which will get the "dbplyr_" prefix). 

* A new testing helper `connection_clean_up()` is added that is used at the end of tests that use a data base backend.
This function looks for the existence of `dbplyr_###` tables and gives a warning if they exists. Then it closes the connection to the data base.

### Known issues
~~This PR also contains the code being merged in~~
* [x] ~~https://github.com/ssi-dk/SCDB/pull/95~~

~~Once merged, this PR will be rebased and opened.~~

### Checklist

* [x] The PR passes all local unit tests
* [x] I have documented any new features introduced
* [x] If the PR adds a new feature, please add an entry in `NEWS.md`
* [x] A reviewer is assigned to this PR

### CODE REVIEW

File: R/update_snapshot.R [hunk 1]
```diff
@@ -164,6 +165,7 @@ update_snapshot <- function(.data, conn, db_table, timestamp, filters = NULL, me
                                 dplyr::select(.data, "checksum")) |>
       dplyr::compute() # Something has changed in dbplyr (2.2.1) that makes this compute needed.
     # Code that takes 20 secs with can be more than 30 minutes to compute without...
+    defer_db_cleanup(to_remove)
```
Comment (LasseEngboChr) [inline R/update_snapshot.R:168]: Later code depends on to_remove ... let us discuss

File: tests/testthat/test-Logger.R [hunk 2]
```diff
@@ -215,10 +215,10 @@ test_that("Logger sets log_file to NULL in DB if not writing to file", {
     expect_length(db_log_file, 1)
     expect_match(db_log_file, "^.+$")
 
-    logger$finalize()
 
+    connection_clean_up(conn)
```
Comment (LasseEngboChr) [inline tests/testthat/test-Logger.R:219]: Shouldn't this be called after logger$finalize() as the cleanup closes the connection and then finalize does not pass the initial if statement

File: R/update_snapshot.R (hunk 1 above)
Comment (RasmusSkytte) [reply R/update_snapshot.R:168]: `defer_db_cleanup()` deletes the table once its parent (`update_snapshot`) exits. By that time, `to_remove` has been used to update the table and should no longer be needed.

**Review by LasseEngboChr — APPROVED** [review]
